name: ci/cd

on:
  push:
    branches:
    - "main"

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    name: Build docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build local
        uses: docker/build-push-action@v6
        with:
          context: .
          no-cache: true
          push: true
          tags: guxkung/imds_cli:amd64
